### ISSUE TITLE
How to remove WAIT action

### ISSUE THREAD

**Issue by furkancanturk** [Jiaoyang-Li/EECBS#3]
Is there a quick way to disallow agents to wait? Otherwise, which classes I need to change?

**Comment by Jiaoyang-Li** [comment]
I believe that commenting out this line is enough:
https://github.com/Jiaoyang-Li/EECBS/blob/fe43ce786d2a9b57f8f1c7cfc866314f2645db31/src/SpaceTimeAStar.cpp#L82

**Comment by furkancanturk** [comment]
It works, thank you!
