### ISSUE TITLE
When the robot occupies multiple nodes

### ISSUE THREAD

**Issue by Navifra-Sally** [Jiaoyang-Li/EECBS#9]
Hello, I am someone who uses code. I am having a problem with using an irregular map without a grid. The issue is that the robot occupies multiple nodes, and when detecting collisions and applying conflict constraints, I want to apply vertex constraints to all the nodes occupied by the robot's size. Can you help me with this?

**Comment by Jiaoyang-Li** [comment]
You can take a look at these two papers:
https://jiaoyangli.me/publications/ZhangSoCS22mutex/
https://jiaoyangli.me/publications/LiAAAI19large/
